server:
  port: 8080
spring:
  datasource:
    username: root
    password: 1Parolef*
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

indexing-settings:
  sites:

#    - url: https://nopaper.ru/
#      name: https://nopaper.ru/
#    - url: https://radiomv.ru/
#      name: https://radiomv.ru/
#    - url: https://et-cetera.ru/mobile/
#      name: et-cetera.ru
#    - url: https://www.cialef.com/
#      name: https://www.cialef.com/
#    - url: https://nopaper.ru/
#      name: https://nopaper.ru/
    - url: https://dombulgakova.ru/
      name: https://dombulgakova.ru/

jsoup-setting:
  Jsoup:
    userAgent: Mozilla/5.0 (Windows; U; Windows NT 6.1; ru-RU) AppleWebKit/534.16 (KHTML, like Gecko) Chrome/10.0.648.11 Safari/534.16
    referrer: https://www:google.com
    timeout: 10000
    ignoreHttpErrors: true
    followRedirects: false