server:
  port: 8080

spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1Parolef*
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        generate_statistics: false
        jdbc:
          order_inserts: true
          batch_size: 200


    hibernate:
      ddl-auto: update
    show-sql: false

indexing-settings:
  sites:

#    - url: https://nopaper.ru/
#      name: https://nopaper.ru/
#    - url: https://radiomv.ru/
#      name: https://radiomv.ru/
    - url: https://et-cetera.ru/mobile/
      name: et-cetera.ru
    - url: https://dombulgakova.ru/
      name: https://dombulgakova.ru/
#    - url: https://playback.ru/
#      name: https://playback.ru/
#    - url: https://skillbox.ru/
#      name: https://skillbox.ru/


jsoup-setting:
  Jsoup:
    userAgent: Mozilla/5.0 (Windows; U; Windows NT 6.1; ru-RU) AppleWebKit/534.16 (KHTML, like Gecko) Chrome/10.0.648.11 Safari/534.16
    referrer: https://www:google.com
    timeout: 10000
    ignoreHttpErrors: true
    followRedirects: false