server:
  port: 8080

spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1Parolef*
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true

  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.MySQLDialect
        generate_statistics: false
        jdbc:
          order_inserts: true
          batch_size: 200


    hibernate:
      ddl-auto: update
    show-sql: false

indexing-settings:
  sites:

#    - url: https://radiomv.ru/
#      name: https://radiomv.ru/
    - url: https://et-cetera.ru/mobile/
      name: et-cetera mobail
    - url: https://dombulgakova.ru/
      name: dombulgakova
    - url: https://playback.ru/
      name: playback
    - url: https://www.svetlovka.ru/
      name: svetlovka


jsoup-setting:
  useragent: Mozilla/5.0 (Windows; U; Windows NT 6.1; ru-RU) AppleWebKit/534.16 (KHTML, like Gecko) Chrome/10.0.648.11 Safari/534.16

  timeout: 100000
  ignoreHttpErrors: true
  sleep: 500

url:
  mediaRegex: '(.*/)*.+\\.(png|jpg|gif|bmp|jpeg|PNG|JPG|GIF|BMP|pdf|php|zip)$|[?|#]'
  ignoreStatusCode: '[45]\d{2}'

batch:
  parse: 200
  lemma: 100
  index: 100
  indexWrite: 200000

search:
  percentAccept: 80
  lruSize: 20

lemma:
  wordType: '\W\w&&[^А-Яа-яёЁ\s]'
  particlesNames: МЕЖД, ПРЕДЛ, СОЮЗ, ЧАСТ, МС, МС-П, ВВОДН

snippet:
  maxLength: 250
  tagsLength: 7
  wordsBeforeSearchQuery: 7
  charsBeforeSearchQuery: 150
  countWordsAfterCutting: 5
